version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: java_backend
      POSTGRES_USER: khaibq
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
      - E:/share/database:/home/database
    networks:
      - my-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - my-network

  # Spring Boot application service
  springbootapp:
    image: java-backend:latest
    container_name: springbootapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java_backend
      SPRING_DATASOURCE_USERNAME: khaibq
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_MAIL_USERNAME: khaibq1.vss@gmail.com
      SPRING_MAIL_PASSWORD: xxxxxxxxxxxxxxxxxx
      TOKEN_JWT_SECRET: AKHKSJHOIUDOFSHDFJBNKC19283JSBKVBVY12312397123HKJB
    volumes:
      - E:/share/app:/home/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  pgdata: